services:
  gateway:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - .docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - .docker/nginx/snippets:/etc/nginx/snippets:ro
      - ./dist:/var/www/virtual/${DOMAIN}/htdocs:ro
      - .docker/letsencrypt/${DOMAIN}/.well-known:/var/www/virtual/${DOMAIN}/htdocs/.well-known:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - php-fpm:/run/php:rw
    healthcheck:
      test: curl --fail http://127.0.0.1/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: on-failure
    depends_on:
      - api
      - php-fpm
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - internal
  api:
    build:
      context: ./api
    environment:
      - SERVER_PORT=3000
      - SERVER_HOST=0.0.0.0
    healthcheck:
      test: curl --fail http://127.0.0.1/api/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: on-failure
    networks:
      - internal
  php-fpm:
    build:
      context: .docker/php-fpm
    volumes:
      - .docker/php-fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - .docker/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./dist:/var/www/html:rw
      - php-fpm:/run/php:rw
    
networks:
  default:
    driver: bridge
  internal:
    internal: true
volumes:
  php-fpm: